# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(upload_to='media/items'),
        ),
    ]
