# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderdetail_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateField(auto_now=True),
        ),
    ]
