# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20160805_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='document',
            field=models.ImageField(blank=True, upload_to='media/order-log'),
        ),
        migrations.AddField(
            model_name='orderpayments',
            name='document',
            field=models.ImageField(blank=True, upload_to='media/order-payment'),
        ),
    ]
