# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ci', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
    ]
